version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  server:
    build: ./server
    image: server_image
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=localhost
      - DB_PORT=5432

  gateway:
    build: ./gateway
    image: gateway_image
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

