DROP TABLE IF EXISTS users, items, bookings;

CREATE TABLE IF NOT EXISTS users
(
    id    LONG GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                          NOT NULL,
    email VARCHAR(512)                          NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL unique (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id           LONG GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                          NOT NULL,
    description  VARCHAR(512)                          NOT NULL,
    is_available boolean                               NOT NULL,
    owner        LONG REFERENCES users (id),
    request_id   LONG REFERENCES requests(id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         LONG GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE           NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE           NOT NULL,
    item_id    LONG REFERENCES items (id),
    booker_id  LONG REFERENCES users (id),
    status     boolean
);

CREATE TABLE IF NOT EXISTS requests
(
    id           LONG GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512),
    requestor_id LONG REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        LONG GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(512),
    item_id   LONG REFERENCES items (id),
    author_id LONG REFERENCES users (id)
);